#!/bin/bash

for host in $(cat $1); do echo | openssl s_client -showcerts -servername $host -connect $host:443 2>/dev/null | openssl x509 -inform pem -noout -text | grep -e 'Not Afte' -e 'Subject:' && echo "Host: "$host""; done
